export interface StatConfig {
  id: string;
  name: string;
  tooltip?: string;
  format?: string;
  showWhenExpanded?: boolean;
}

export interface StatReference {
  id: string;
  showWhenExpanded?: boolean;
}

export interface StatCategoryConfig {
  id: string;
  name: string;
  stats: StatReference[];
  isExpanded?: boolean;
}

export interface StatsConfiguration {
  categories: StatCategoryConfig[];
  version: number;
}

export interface AvailableStat {
  name: string;
  type: "percent" | "flat" | "attribute" | "fixed";
  category?: string;
}

// Helper function to resolve stat references to full stat configurations
export const resolveStatReference = (
  statRef: StatReference
): StatConfig | undefined => {
  const baseStat = ALL_AVAILABLE_STATS.find((stat) => stat.id === statRef.id);
  if (!baseStat) return undefined;

  return {
    ...baseStat,
    showWhenExpanded: statRef.showWhenExpanded ?? baseStat.showWhenExpanded,
  };
};

// All available stats with complete format information
export const ALL_AVAILABLE_STATS: StatConfig[] = [
  {
    id: "base-health",
    name: "Base Health",
    tooltip: "Sources: Level Scaling, Infinity, Synergy",
    format: "{value}",
    showWhenExpanded: true,
  },
  {
    id: "health",
    name: "Health",
    tooltip: "Sources: Items, Durability, Trait 3",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "max-health",
    name: "Max Health",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "spirit1",
    name: "Spirit",
    tooltip: "Sources: Level Scaling, Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "spirit2",
    name: "Secondary Resource",
    tooltip: "Sources: Level Scaling, Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "spirit-on-hit",
    name: "Spirit On Hit",
    tooltip: "Sources: Items, Synergy",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "spirit-on-kill",
    name: "Spirit On Kill",
    tooltip: "Sources: Items, Synergy",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "resource-cost",
    name: "Resource Cost",
    tooltip: "Sources: Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "power-duration",
    name: "Power Duration",
    tooltip: "Sources: Items",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "power-radius",
    name: "Power Radius",
    tooltip: "Sources: Items",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "move-speed",
    name: "Move Speed",
    tooltip: "Sources: Infinity, Synergy, Items",
    format: "{value.0d}",
    showWhenExpanded: false,
  },
  {
    id: "medkit-cooldown",
    name: "Medkit Cooldown",
    tooltip: "Sources: Trait 3, Infinity, Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "avg-effective-health",
    name: "Avg. Effective Health",
    format: "{value.0d}",
    showWhenExpanded: false,
  },
  {
    id: "dmg-reduction",
    name: "DMG Reduction% (+)",
    tooltip: "Sources: Combat Type, Items",
    format: "+{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-dmg-reduction",
    name: "DMG Reduction%",
    tooltip: "Sources: 100% of Defense%, 20% of Deflect%, 40% of Dodge%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "defense-rating",
    name: "Defense Rating",
    tooltip: "Archetype 2, Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "defense-multi",
    name: "Defense Multi.",
    tooltip: "Durability, Archetype 2, Infinity, Synergy",
    format: "{value.0d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-defense",
    name: "Defense%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "deflect-rating",
    name: "Deflect Rating",
    tooltip: "Sources: Archetype 2, Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "deflect-multi",
    name: "Deflect Multi.",
    tooltip: "Sources: Strength, Archetype 2, Synergy",
    format: "{value.0d}%",
    showWhenExpanded: true,
  },
  {
    id: "plus-deflect",
    name: "Deflect% (+)",
    tooltip: "Sources: Trait 3, Infinity",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-deflect",
    name: "Deflect%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "deflect-to-dmg-reduction",
    name: "Deflect% to DMG Reduction%",
    tooltip: "40% of Deflect%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "dodge-rating",
    name: "Dodge Rating",
    tooltip: "Sources: Archetype 2, Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "dodge-multi",
    name: "Dodge Multi.",
    tooltip: "Sources: Speed, Archetype 2, Synergy",
    format: "{value.0d}%",
    showWhenExpanded: true,
  },
  {
    id: "plus-dodge",
    name: "Dodge% (+)",
    tooltip: "Sources: Trait 3, Infinity",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-dodge",
    name: "Dodge%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "dodge-to-dmg-reduction",
    name: "Dodge% to DMG Reduction%",
    tooltip: "20% of Dodge%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "health-regen",
    name: "Health Regen.",
    tooltip: "Sources: Trait 3, Items",
    format: "{value}/s",
    showWhenExpanded: false,
  },
  {
    id: "health-regen-medkit",
    name: "Health Regen. On Medkit Use",
    tooltip: "Sources: Trait 3, Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "health-on-hit",
    name: "Health On Hit",
    tooltip: "Sources: Trait 3, Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "tenacity",
    name: "Tenacity",
    tooltip: "Sources: Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "reduced-dmg-from-deflected",
    name: "Reduced DMG from Deflected",
    tooltip: "Sources: Strength, Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "reduced-dmg-from-melee",
    name: "Reduced DMG from Melee",
    tooltip: "Sources: Fighting, Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "reduced-dmg-from-area",
    name: "Reduced DMG from Area",
    tooltip: "Sources: Speed, Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "reduced-dmg-from-ranged",
    name: "Reduced DMG from Ranged",
    tooltip: "Sources: Energy, Items",
    format: "-{value}%",
    showWhenExpanded: false,
  },
  {
    id: "raw-attack-speed",
    name: "Raw Attack Speed",
    tooltip: "Sources: Items, Synergy, Infinity",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "attack-speed",
    name: "Attack Speed",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "base-dmg",
    name: "Base DMG",
    tooltip: "Sources: Primary Attributes",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-rating",
    name: "DMG Rating",
    tooltip: "Sources: Items",
    format: "{value}",
    showWhenExpanded: false,
  },
  {
    id: "total-dmg",
    name: "DMG%",
    tooltip: "Sources: Converted DMG Rating",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "physical-dmg-rating",
    name: "Physical DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "physical-base-dmg",
    name: "Physical Base DMG%",
    tooltip: "Sources: Team-up Items, Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-physical-dmg",
    name: "Physical DMG%",
    tooltip:
      "Sources: Converted DMG Rating and Physical DMG Rating; Physical Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "energy-dmg-rating",
    name: "Energy DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "energy-base-dmg",
    name: "Energy Base DMG%",
    tooltip: "Sources: Team-up Items, Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-energy-dmg",
    name: "Energy DMG%",
    tooltip:
      "Sources: Converted DMG Rating and Energy DMG Rating; Energy Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "mental-dmg-rating",
    name: "Mental DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "mental-base-dmg",
    name: "Mental Base DMG%",
    tooltip: "Sources: Converted DMG Rating and Mental DMG Rating",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-mental-dmg",
    name: "Mental DMG%",
    tooltip:
      "Sources: Converted DMG Rating and Mental DMG Rating; Mental Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "melee-dmg-rating",
    name: "Melee DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "melee-base-dmg",
    name: "Melee Base DMG%",
    tooltip: "Sources: Team-up Items, Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-melee-dmg",
    name: "Melee DMG%",
    tooltip: "Sources: Converted Melee DMG Rating; Melee Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "ranged-dmg-rating",
    name: "Ranged DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "ranged-base-dmg",
    name: "Ranged Base DMG%",
    tooltip: "Sources: Team-up Items, Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-ranged-dmg",
    name: "Ranged DMG%",
    tooltip: "Sources: Converted Ranged DMG Rating; Ranged Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "summon-dmg-rating",
    name: "Summon DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "summon-base-dmg",
    name: "Summon Base DMG%",
    tooltip: "Sources: Trait 1, Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-summon-dmg",
    name: "Summon DMG%",
    tooltip: "Sources: Converted Summon DMG Rating; Summon Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "area-dmg-rating",
    name: "Area DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "area-base-dmg",
    name: "Area Base DMG%",
    tooltip: "Sources: Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-area-dmg",
    name: "Area DMG%",
    tooltip: "Sources: Converted Area DMG Rating; Area Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "movement-dmg-rating",
    name: "Movement DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "movement-base-dmg",
    name: "Movement Base DMG%",
    tooltip: "Sources: Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-movement-dmg",
    name: "Movement DMG%",
    tooltip: "Sources: Converted Movement DMG Rating; Movement Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "signature-dmg-rating",
    name: "Signature DMG Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "signature-base-dmg",
    name: "Signature Base DMG%",
    tooltip: "Sources: Synergy",
    format: "{value.1d}%",
    showWhenExpanded: true,
  },
  {
    id: "total-signature-dmg",
    name: "Signature DMG%",
    tooltip: "Sources: Converted Signature DMG Rating; Signature Base DMG%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "crit-dmg-rating",
    name: "Crit DMG Rating",
    tooltip: "Sources: Intelligence, Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "plus-crit-dmg",
    name: "Crit DMG%",
    tooltip: "Sources: Trait 1, Synergy, Infinity",
    format: "+{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-crit-dmg",
    name: "Crit DMG%",
    format: "{value.0d}%",
    showWhenExpanded: false,
  },
  {
    id: "crit-hit-rating",
    name: "Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "crit-hit-multi",
    name: "Crit Hit Multi.",
    tooltip: "Sources: Fighting, Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "plus-crit-hit",
    name: "Crit Hit% (+)",
    tooltip: "Sources: Trait 1, Infinity",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-crit-hit",
    name: "Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "physical-crit-hit-rating",
    name: "Physical Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "physical-crit-hit-multi",
    name: "Physical Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "physical-crit-hit",
    name: "Physical Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "energy-crit-hit-rating",
    name: "Energy Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "energy-crit-hit-multi",
    name: "Energy Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "energy-crit-hit",
    name: "Energy Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "mental-crit-hit-rating",
    name: "Mental Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "mental-crit-hit-multi",
    name: "Mental Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "mental-crit-hit",
    name: "Mental Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "melee-crit-hit-rating",
    name: "Melee Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "melee-crit-hit-multi",
    name: "Melee Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "melee-crit-hit",
    name: "Melee Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "ranged-crit-hit-rating",
    name: "Ranged Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "ranged-crit-hit-multi",
    name: "Ranged Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "ranged-crit-hit",
    name: "Ranged Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "area-crit-hit-rating",
    name: "Area Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "area-crit-hit-multi",
    name: "Area Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "area-crit-hit",
    name: "Area Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "movement-crit-hit-rating",
    name: "Movement Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "movement-crit-hit-multi",
    name: "Movement Crit Hit Multi.",
    tooltip: "Sources: Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "movement-crit-hit",
    name: "Movement Crit Hit%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "brutal-strike-rating",
    name: "Brutal Strike Rating",
    tooltip: "Sources: Items",
    format: "{value}",
    showWhenExpanded: true,
  },
  {
    id: "brutal-strike-multi",
    name: "Brutal Strike Multi.",
    tooltip: "Sources: Fighting, Synergy",
    format: "{value}%",
    showWhenExpanded: true,
  },
  {
    id: "plus-brutal-strike",
    name: "Brutal Strike% (+)",
    tooltip: "Sources: Trait 1, Infinity",
    format: "+{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-brutal-strike",
    name: "Brutal Strike%",
    format: "{value.1d}%",
    showWhenExpanded: false,
  },
  {
    id: "brutal-dmg-rating",
    name: "Brutal DMG Rating",
    tooltip: "Sources: Intelligence, Items",
    format: "{value.0d}",
    showWhenExpanded: true,
  },
  {
    id: "plus-brutal-dmg",
    name: "Brutal DMG% (+)",
    tooltip: "Sources: Trait 1, Synergy, Infinity",
    format: "+{value}%",
    showWhenExpanded: true,
  },
  {
    id: "total-brutal-dmg",
    name: "Brutal DMG%",
    format: "{value.0d}%",
    showWhenExpanded: false,
  },
  {
    id: "summoned-ally-health",
    name: "Summoned Ally Health",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "summoned-ally-duration",
    name: "Summoned Ally Duration",
    tooltip: "Sources: Items",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "summoned-ally-crit-hit-rating",
    name: "Summoned Ally Crit Hit Rating",
    tooltip: "Sources: Items",
    format: "{value.0d}",
    showWhenExpanded: false,
  },
  {
    id: "summoned-ally-dmg",
    name: "Summoned Ally DMG%",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-normals-elites",
    name: "Normals/Elites",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-champions",
    name: "Champions",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-bosses",
    name: "Bosses",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-targeting-you",
    name: "DMG vs Targeting You",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-not-targeting-you",
    name: "DMG vs Not Targeting You",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-unaware-targets",
    name: "DMG vs Unaware Targets",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-weakened",
    name: "DMG vs Weakened",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-stunned",
    name: "DMG vs Stunned",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-slowed",
    name: "DMG vs Slowed",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-knockdown",
    name: "DMG vs Knockdown",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-chilled",
    name: "DMG vs Chilled",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-frozen",
    name: "DMG vs Frozen",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-vulnerable",
    name: "DMG vs Vulnerable",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-taunted",
    name: "DMG vs Taunted",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-petrified",
    name: "DMG vs Petrified",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-constricted-webbing",
    name: "DMG vs Constricted Webbing",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-dot-affected",
    name: "DMG vs DoT Affected",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-feared",
    name: "DMG vs Feared",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-bleeding",
    name: "DMG vs Bleeding",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-burning",
    name: "DMG vs Burning",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-hellfire",
    name: "DMG vs Hellfire",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-machines",
    name: "DMG vs Machines",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-demon-status",
    name: "DMG vs Demon Status",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
  {
    id: "dmg-vs-danger-room-status",
    name: "DMG vs Danger Room Status",
    tooltip: "Sources: Items, Synergy",
    format: "{value}%",
    showWhenExpanded: false,
  },
];

// Default stat configurations - only contains stat IDs, full definitions come from ALL_AVAILABLE_STATS
export const DEFAULT_STATS_CONFIG: StatsConfiguration = {
  categories: [
    {
      id: "general",
      name: "General",
      stats: [{ id: "base-health" }, { id: "max-health" }],
    },
    {
      id: "defensive",
      name: "Defensive",
      stats: [
        //{ id: "avg-effective-health" },
        { id: "dmg-reduction" },
        { id: "total-dmg-reduction" },
        { id: "defense-rating" },
        { id: "defense-multi" },
        { id: "total-defense" },
        { id: "deflect-rating" },
        { id: "deflect-multi" },
        { id: "plus-deflect" },
        { id: "total-deflect" },
        { id: "deflect-to-dmg-reduction" },
        { id: "dodge-rating" },
        { id: "dodge-multi" },
        { id: "plus-dodge" },
        { id: "total-dodge" },
        { id: "dodge-to-dmg-reduction" },
        { id: "health-regen" },
        { id: "health-regen-medkit" },
        { id: "health-on-hit" },
        { id: "summoned-ally-health" },
        { id: "tenacity" },
      ],
    },
    {
      id: "offensive",
      name: "Offensive",
      stats: [
        { id: "raw-attack-speed" },
        { id: "attack-speed" },
        { id: "crit-hit-rating" },
        { id: "crit-hit-multi" },
        { id: "plus-crit-hit" },
        { id: "total-crit-hit" },
        { id: "melee-crit-hit-rating" },
        { id: "melee-crit-hit-multi" },
        { id: "melee-crit-hit" },
        { id: "ranged-crit-hit-rating" },
        { id: "ranged-crit-hit-multi" },
        { id: "ranged-crit-hit" },
        { id: "physical-crit-hit-rating" },
        { id: "physical-crit-hit-multi" },
        { id: "physical-crit-hit" },
        { id: "energy-crit-hit-rating" },
        { id: "energy-crit-hit-multi" },
        { id: "energy-crit-hit" },
        { id: "mental-crit-hit-rating" },
        { id: "mental-crit-hit-multi" },
        { id: "mental-crit-hit" },
        { id: "area-crit-hit-rating" },
        { id: "area-crit-hit-multi" },
        { id: "area-crit-hit" },
        { id: "crit-dmg-rating" },
        { id: "plus-crit-dmg" },
        { id: "total-crit-dmg" },
        { id: "brutal-strike-rating" },
        { id: "brutal-strike-multi" },
        { id: "plus-brutal-strike" },
        { id: "total-brutal-strike" },
        { id: "brutal-dmg-rating" },
        { id: "plus-brutal-dmg" },
        { id: "total-brutal-dmg" },
        { id: "base-dmg" },
        { id: "dmg-rating" },
        { id: "total-dmg" },
        { id: "physical-dmg-rating" },
        { id: "physical-base-dmg" },
        { id: "total-physical-dmg" },
        { id: "energy-dmg-rating" },
        { id: "energy-base-dmg" },
        { id: "total-energy-dmg" },
        { id: "mental-dmg-rating" },
        { id: "mental-base-dmg" },
        { id: "total-mental-dmg" },
        { id: "melee-dmg-rating" },
        { id: "melee-base-dmg" },
        { id: "total-melee-dmg" },
        { id: "ranged-dmg-rating" },
        { id: "ranged-base-dmg" },
        { id: "total-ranged-dmg" },
        { id: "summon-dmg-rating" },
        { id: "summon-base-dmg" },
        { id: "total-summon-dmg" },
        { id: "area-dmg-rating" },
        { id: "area-base-dmg" },
        { id: "total-area-dmg" },
        { id: "movement-dmg-rating" },
        { id: "movement-base-dmg" },
        { id: "total-movement-dmg" },
      ],
    },
    {
      id: "utility",
      name: "Utility",
      stats: [
        { id: "spirit-on-hit" },
        { id: "resource-cost" },
        { id: "move-speed" },
        { id: "power-duration" },
      ],
    },
  ],
  version: 1,
};

// stat_id:stat_name
// finalStats[stat_name]
export const STAT_ID_TO_NAME_MAP: Record<string, string> = {
  "base-health": "Base Health",
  health: "Health",
  "max-health": "Max Health",
  spirit1: "Spirit1",
  spirit2: "Spirit2",
  "spirit-on-hit": "Spirit On Hit",
  "spirit-on-kill": "Spirit On Kill",
  "resource-cost": "Resource Cost",
  "power-duration": "Power Duration",
  "power-radius": "Power Radius",
  "move-speed": "Move Speed",
  "medkit-cooldown": "Medkit Cooldown",
  //"avg-effective-health": "Avg. Effective Health",
  "dmg-reduction": "DMG Reduction% (+)",
  "total-dmg-reduction": "Total DMG Reduction %",
  "defense-rating": "Defense Rating",
  "defense-multi": "Defense Multi.",
  "total-defense": "Total Defense%",
  "deflect-rating": "Deflect Rating",
  "deflect-multi": "Deflect Multi.",
  "plus-deflect": "Deflect% (+)",
  "total-deflect": "Total Deflect%",
  "deflect-to-dmg-reduction": "Deflect% to DMG Reduction%",
  "dodge-rating": "Dodge Rating",
  "dodge-multi": "Dodge Multi.",
  "plus-dodge": "Dodge% (+)",
  "total-dodge": "Total Dodge%",
  "dodge-to-dmg-reduction": "Dodge% to DMG Reduction%",
  "health-regen": "Health Regen.",
  "health-regen-medkit": "Health Regen. On Medkit",
  "health-on-hit": "Health On Hit",
  tenacity: "Tenacity",
  "reduced-dmg-from-deflected": "Reduced DMG from Deflected",
  "reduced-dmg-from-melee": "Reduced DMG from Melee",
  "reduced-dmg-from-area": "Reduced DMG from Area",
  "reduced-dmg-from-ranged": "Reduced DMG from Ranged",
  "raw-attack-speed": "Raw Attack Speed",
  "attack-speed": "Attack Speed",
  "base-dmg": "Base DMG",
  "dmg-rating": "DMG Rating",
  "total-dmg": "DMG%",
  "physical-dmg-rating": "Physical DMG Rating",
  "physical-base-dmg": "Physical Base DMG%",
  "total-physical-dmg": "Total Physical DMG%",
  "energy-dmg-rating": "Energy DMG Rating",
  "energy-base-dmg": "Energy Base DMG%",
  "total-energy-dmg": "Total Energy DMG%",
  "mental-dmg-rating": "Mental DMG Rating",
  "mental-base-dmg": "Mental Base DMG%",
  "total-mental-dmg": "Total Mental DMG%",
  "melee-dmg-rating": "Melee DMG Rating",
  "melee-base-dmg": "Melee Base DMG%",
  "total-melee-dmg": "Total Melee DMG%",
  "ranged-dmg-rating": "Ranged DMG Rating",
  "ranged-base-dmg": "Ranged Base DMG%",
  "total-ranged-dmg": "Total Ranged DMG%",
  "summon-dmg-rating": "Summon DMG Rating",
  "summon-base-dmg": "Summon Base DMG%",
  "total-summon-dmg": "Total Summon DMG%",
  "area-dmg-rating": "Area DMG Rating",
  "area-base-dmg": "Area Base DMG%",
  "total-area-dmg": "Total Area DMG%",
  "movement-dmg-rating": "Movement DMG Rating",
  "movement-base-dmg": "Movement Base DMG%",
  "total-movement-dmg": "Total Movement DMG%",
  "signature-dmg-rating": "Signature DMG Rating",
  "signature-base-dmg": "Signature Base DMG%",
  "total-signature-dmg": "Total Signature DMG%",
  "crit-dmg-rating": "Crit DMG Rating",
  "plus-crit-dmg": "Crit DMG%",
  "total-crit-dmg": "Total Crit DMG%",
  "crit-hit-rating": "Crit Hit Rating",
  "crit-hit-multi": "Crit Hit Multi.",
  "plus-crit-hit": "Crit Hit% (+)",
  "total-crit-hit": "Total Crit Hit%",
  "physical-crit-hit-rating": "Physical Crit Hit Rating",
  "physical-crit-hit-multi": "Physical Crit Hit Multi.",
  "physical-crit-hit": "Physical Crit Hit%",
  "energy-crit-hit-rating": "Energy Crit Hit Rating",
  "energy-crit-hit-multi": "Energy Crit Hit Multi.",
  "energy-crit-hit": "Energy Crit Hit%",
  "mental-crit-hit-rating": "Mental Crit Hit Rating",
  "mental-crit-hit-multi": "Mental Crit Hit Multi.",
  "mental-crit-hit": "Mental Crit Hit%",
  "melee-crit-hit-rating": "Melee Crit Hit Rating",
  "melee-crit-hit-multi": "Melee Crit Hit Multi.",
  "melee-crit-hit": "Melee Crit Hit%",
  "ranged-crit-hit-rating": "Ranged Crit Hit Rating",
  "ranged-crit-hit-multi": "Ranged Crit Hit Multi.",
  "ranged-crit-hit": "Ranged Crit Hit%",
  "area-crit-hit-rating": "Area Crit Hit Rating",
  "area-crit-hit-multi": "Area Crit Hit Multi.",
  "area-crit-hit": "Area Crit Hit%",
  "movement-crit-hit-rating": "Movement Crit Hit Rating",
  "movement-crit-hit-multi": "Movement Crit Hit Multi.",
  "movement-crit-hit": "Movement Crit Hit%",
  "brutal-strike-rating": "Brutal Strike Rating",
  "brutal-strike-multi": "Brutal Strike Multi.",
  "plus-brutal-strike": "Brutal Strike% (+)",
  "total-brutal-strike": "Total Brutal Strike%",
  "brutal-dmg-rating": "Brutal DMG Rating",
  "plus-brutal-dmg": "Brutal DMG% (+)",
  "total-brutal-dmg": "Total Brutal DMG%",
  "summoned-ally-health": "Summoned Ally Health",
  "summoned-ally-duration": "Summoned Ally Duration",
  "summoned-ally-crit-hit-rating": "Summoned Ally Crit Hit Rating",
  "summoned-ally-dmg": "Summoned Ally DMG%",
  "dmg-vs-normals-elites": "DMG vs Normals/Elites",
  "dmg-vs-champions": "DMG vs Champions",
  "dmg-vs-bosses": "DMG vs Bosses",
  "dmg-vs-targeting-you": "DMG vs Targeting You",
  "dmg-vs-not-targeting-you": "DMG vs Not Targeting You",
  "dmg-vs-unaware-targets": "DMG vs Unaware Targets",
  "dmg-vs-weakened": "DMG vs Weakened",
  "dmg-vs-stunned": "DMG vs Stunned",
  "dmg-vs-slowed": "DMG vs Slowed",
  "dmg-vs-knockdown": "DMG vs Knockdown",
  "dmg-vs-chilled": "DMG vs Chilled",
  "dmg-vs-frozen": "DMG vs Frozen",
  "dmg-vs-vulnerable": "DMG vs Vulnerable",
  "dmg-vs-taunted": "DMG vs Taunted",
  "dmg-vs-petrified": "DMG vs Petrified",
  "dmg-vs-constricted-webbing": "DMG vs Constricted Webbing",
  "dmg-vs-dot-affected": "DMG vs DoT Affected",
  "dmg-vs-feared": "DMG vs Feared",
  "dmg-vs-bleeding": "DMG vs Bleeding",
  "dmg-vs-burning": "DMG vs Burning",
  "dmg-vs-hellfire": "DMG vs Hellfire",
  "dmg-vs-machines": "DMG vs Machines",
  "dmg-vs-demon-status": "DMG vs Demon Status",
  "dmg-vs-danger-room-status": "DMG vs Danger Room Status",
};
